"""Sharing utilities — prepare a vault for git distribution."""

from __future__ import annotations

import logging
import re
from pathlib import Path

import yaml

log = logging.getLogger(__name__)


def init_vault(
    vault_dir: str | Path,
    title: str | None = None,
    author: str | None = None,
) -> None:
    """Prepare a vault for sharing: README.md, .gitignore, stats."""
    vault = Path(vault_dir)
    if not vault.exists():
        raise FileNotFoundError(f"Vault not found: {vault}")

    # Gather stats
    stats = _vault_stats(vault)

    # Infer title/author from _index.md if not provided
    index = vault / "_index.md"
    if index.exists() and (not title or not author):
        text = index.read_text(encoding="utf-8")
        if not title:
            m = re.search(r"^# (.+)$", text, re.MULTILINE)
            title = m.group(1) if m else vault.name
        if not author:
            m = re.search(r"\*by (.+?)[\s(]", text)
            author = m.group(1).strip() if m else "Unknown"

    title = title or vault.name
    author = author or "Unknown"

    # Write .gitignore
    gitignore = vault / ".gitignore"
    gitignore.write_text(
        ".obsidian/workspace.json\n"
        ".obsidian/cache\n"
        ".obsidian/workspace-mobile.json\n"
        ".DS_Store\n"
        "*.tmp\n",
        encoding="utf-8",
    )

    # Write README.md
    readme = vault / "README.md"
    slug = vault.name.lower().replace(" ", "-")
    readme.write_text(
        f"# {title}\n\n"
        f"*by {author}*\n\n"
        f"A distillary knowledge vault generated by [Fractal](https://github.com/distillary-vault/fractal).\n\n"
        f"## Stats\n\n"
        f"| Metric | Value |\n"
        f"|---|---|\n"
        f"| Total notes | {stats['total']} |\n"
        f"| Claims | {stats['claims']} |\n"
        f"| Entities | {stats['entities']} |\n"
        f"| Atomic claims | {stats['atoms']} |\n"
        f"| Structure notes | {stats['structure']} |\n"
        f"| Link resolution | {stats['resolution_pct']}% |\n\n"
        f"## How to use\n\n"
        f"1. Clone this repo\n"
        f"2. Open the folder as an Obsidian vault\n"
        f"3. Start with `_index.md`\n"
        f"4. Enable the **Bases** core plugin for database views\n"
        f"5. Enable the CSS snippet in `.obsidian/snippets/`\n\n"
        f"## Tags\n\n"
        f"`distillary-vault` `{slug}`\n",
        encoding="utf-8",
    )

    log.info("init_vault: wrote .gitignore and README.md to %s", vault)
    print(f"Vault ready to share:")
    print(f"  cd {vault}")
    print(f"  git init && git add . && git commit -m 'Distillary vault: {title}'")
    print(f"  gh repo create distillary-vault-{slug} --public --push")


def _vault_stats(vault: Path) -> dict:
    """Gather basic stats from a vault."""
    total = claims = entities = atoms = structure = 0
    all_stems = set()
    all_links = set()
    resolved = 0

    for md in vault.rglob("*.md"):
        if ".obsidian" in str(md):
            continue
        total += 1
        all_stems.add(md.stem)
        text = md.read_text(encoding="utf-8", errors="replace")

        if "kind: claim" in text:
            claims += 1
        if "kind: entity" in text:
            entities += 1
        if "layer: 0" in text:
            atoms += 1
        if "layer: 1" in text:
            structure += 1

        for link in re.findall(r"\[\[([^\]]+)\]\]", text):
            all_links.add(link)

    resolved = sum(1 for l in all_links if l in all_stems)
    resolution_pct = round(100 * resolved / max(len(all_links), 1), 1)

    return {
        "total": total,
        "claims": claims,
        "entities": entities,
        "atoms": atoms,
        "structure": structure,
        "resolution_pct": resolution_pct,
    }
